# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  apt_packages:
    - build-essential
    - wget
    - tar
  jobs:
    post_create_environment:
    - pip install poetry

    pre_install:
    # Install TA-Lib
    - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    - tar -xvzf ta-lib-0.4.0-src.tar.gz
    - mkdir -p ${READTHEDOCS_REPOSITORY_PATH}/talib
    - cd ta-lib/ && ./configure --prefix=${READTHEDOCS_REPOSITORY_PATH}/talib && make && make install && cd .. && rm -rf ta-lib ta-lib-0.4.0-src.tar.gz
    # - cd ta-lib/ && ./configure --prefix=/usr && make && make install && cd .. && rm -rf ta-lib ta-lib-0.4.0-src.tar.gz
    - export TA_LIBRARY_PATH=$READTHEDOCS_REPOSITORY_PATH/talib/lib
    - export TA_INCLUDE_PATH=$READTHEDOCS_REPOSITORY_PATH/talib/include
    # - export TA_LIBRARY_PATH=${READTHEDOCS_REPOSITORY_PATH}/talib/lib
    # - export TA_INCLUDE_PATH=${READTHEDOCS_REPOSITORY_PATH}/talib/include

    post_install:
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs


# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#   install:
#   - requirements: docs/requirements.txt
