# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  trader:
    restart: always
    build:
      context: ./
      # dockerfile: docker/trader.Dockerfile # This is for strategy in the strategies directory, just make sure your have a pyproject.toml file in the root directory
      dockerfile: Docker/localTrader.Dockerfile # like trader.Dockerfile but for internal use - local framework source code
      args:
        STRATEGY: ${STRATEGY:-SuperTrendStrategy}
    ports:
      - 50000:50000
      - 8050:8050
    env_file:
      # - .env
      - stack.env
    healthcheck:
      # test: ["CMD-SHELL", "nc -vz trader 50000"]
      # test: ["CMD-SHELL", "wget -q --spider trader:8050 -O /dev/null"]
      interval: "5s"
      retries: 300


  
# TODO: Add Timescale Postgres or MongoDB database service here.
# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt
