from __future__ import annotations
import abc
from typing import TYPE_CHECKING, List, Optional, override

from pandas import DataFrame
import pandas_ta as ta
import numpy as np

from OlympusTrader.broker.interfaces import IAsset, IQuote
from OlympusTrader.insight.insight import Insight

if TYPE_CHECKING:
    from ..strategy.base_strategy import BaseStrategy


class AlphaResults():
    """
    ### Alpha Results
    This class is used to store the results of the Alpha.
    """
    insight: Insight
    """Insight generated by the alpha."""
    success: bool
    """Boolean value indicating if the executor was ran successful or not."""
    alpha: str
    """Name of the executor."""
    message: str
    """Message indicating the result of the alpha."""

    def __init__(self, insight: Optional[Insight] = None, success: bool = True, message: str = None, alpha: str = None):
        self.insight = insight
        if insight:
            # If the executor passed, then it was successfully ran
            success = True
        self.success = success
        if self.success == False:
            # If the executor was not successfully ran, then it did not pass
            self.insight = None
        self.message = message
        self.alpha = alpha


class BaseAlpha(abc.ABC):
    """
    ### Abstract class for alpha implementations.
    Used to generate insights based on the strategy.
    """
    NAME: str
    """Name of the alpha model."""
    VERSION: str
    """Version of the alpha model."""

    STRATEGY: BaseStrategy
    """Reference to the strategy instance."""

    TA: List[dict] = []
    """List of technical analysis needed for the alpha model."""

    baseConfidenceModifierField: Optional[str] = None
    """Field to modify base confidence."""

    ALLOWED_ASSETS: Optional[set[str]] = set()
    """Set of allowed assets for the executor"""

    @abc.abstractmethod
    def __init__(self, strategy: BaseStrategy, name: str, version: str = "1.0", baseConfidenceModifierField: Optional[str] = None,  allowed_assets:  Optional[set[str]] = None) -> None:
        self.NAME = name
        self.VERSION = version

        # assert isinstance(strategy, BaseStrategy), "strategy must be of type BaseStrategy."
        # Reference to the strategy instance
        self.STRATEGY = strategy
        if baseConfidenceModifierField:
            self.baseConfidenceModifierField = baseConfidenceModifierField

        if allowed_assets is not None:
            assert isinstance(
                allowed_assets, set), "Allowed assets must be a set"
            self.ALLOWED_ASSETS = allowed_assets
        

    @abc.abstractmethod
    def start(self):
        """Initialize the alpha model once at the start. data, etc. in the state of the Strategy."""
        pass

    @abc.abstractmethod
    def init(self,  asset: IAsset):
        """Initialize the alpha model for each assets. variables, data, etc. in the state of the Strategy."""
        pass

    @abc.abstractmethod
    def generateInsights(self, symbol: str) -> AlphaResults:
        """Generate insights based on the alpha model."""
        pass

    def registerAlpha(self):
        self.STRATEGY.ALPHA_MODELS.append(self)
        # Set the technical analysis needed for the alpha
        self._loadTa()

    def returnResults(self, insight: Optional[Insight] = None, success: bool = True, message: str = None) -> AlphaResults:
        return AlphaResults(insight, success, message, self.NAME)

    def get_history(self, symbol: str) -> DataFrame:
        return self.STRATEGY.history[symbol].loc[symbol]

    def get_latest_bar(self, symbol: str) -> DataFrame:
        return self.get_history(symbol).iloc[-1]

    def get_previos_bar(self, symbol: str) -> DataFrame:
        return self.get_history(symbol).iloc[-2]

    def get_latest_quote(self, asset: IAsset) -> IQuote:
        if asset:
            return self.STRATEGY.broker.get_latest_quote(asset)
        return None    
    def get_asset(self, symbol: str) -> IAsset:
        return self.STRATEGY.UNIVERSE.get(symbol)

    def isAllowedAsset(self, symbol: str) -> bool:
        """Check if the asset is allowed"""
        if self.ALLOWED_ASSETS is None or len(self.ALLOWED_ASSETS) == 0:
            return True
        return symbol in self.ALLOWED_ASSETS

    def get_baseConfidenceModifier(self, symbol: str):
        if self.baseConfidenceModifierField:
            baseConfidenceModifier = self.STRATEGY.state[self.baseConfidenceModifierField][symbol]
            if baseConfidenceModifier:
                return baseConfidenceModifier

        return 1

    def _loadTa(self):
        if self.TA:
            self.STRATEGY.add_ta(self.TA)
